### ISSUE TITLE
Move configs from local.conf.php to _ss_environment.php

### ISSUE THREAD

**Issue by silbinarywolf** [symbiote/silverstripe-build#14]
**Why?**
All define() constants done in _ss_environment.php are usable in caching layers or before building the various ConfigManifest files, etc.

By putting database, environment and log settings in this file, we can update our caching layers use these values and/or store cache configs there. (One centralized place for server configurations sounds like a good idea to me!)

**Silverstripe versions?**
IIRC, _ss_environment.php only works 3.2+, but maybe its in 3.1+ and just not documented.

**Comment by alexclifford** [comment]
This would likely require a restructure to our `mysite/_config.php` templates but if it's doable the benefits sound fine? @nyeholt

**Comment by nglasl** [comment]
Closing this one since everything is now using `.env` for SS 4.
