### ISSUE TITLE
SS4 Flush

### ISSUE THREAD

**Issue by nglasl** [symbiote/silverstripe-build#23]
In SS4, when you run a `phing`, the `/dev/build with flush` step doesn't actually trigger a flush. I've noticed that opening a page after `phing` results in a wall of errors until I append `?flush=1` to the URL. I don't recall this being a problem with SS3, so my assumption is that something underlying has changed.

**Comment by silbinarywolf** [comment]
@nglasl FYI, this is the behaviour you get on Windows by default, which is why I always ran `composer install` and then `phing apply_patches` manually.

Then I just dev/build in browser.

**Comment by nglasl** [comment]
I've put this one down as `effort/hard` as it may end up time consuming to debug. While it is possible to work around, ideally this isn't something you need to remember (unless it explicitly says you need to flush after `phing` has completed). If anyone has a PR for this, or even some ideas where the problem may lie (I'm leaning towards permissions), that would be warmly welcomed :)

**Comment by nglasl** [comment]
I've put this one down as effort/hard as it may end up time consuming to debug. While it is possible to work around, ideally this isn't something you need to remember (unless it explicitly says you need to flush after phing has completed). If anyone has a PR for this, or even some ideas where the problem may lie (I'm leaning towards permissions), that would be warmly welcomed.

**Comment by nglasl** [comment]
This one has been open for over a year, and I can't say it's something that I've noticed recently so perhaps it's resolved. I'm going to close this, and re-open if there's still an issue here.
