### ISSUE TITLE
SilverStripe SQLite module doesn't currently support Polymorphic relationships

### ISSUE THREAD

**Issue by stephenmcm** [symbiote/silverstripe-build#26]
See: [Polymorphic database fields are bad news for reconstruction #45](https://github.com/silverstripe/silverstripe-sqlite3/issues/45)

**Comment by nglasl** [comment]
The base and build modules no longer depend on this, as it has been found to introduce subtle issues during module upgrades (and generally isn't something used in production). Therefore, we've opted to leave this choice up to the developer. If you think something may have been missed during this process, please do let us know.
